### ISSUE TITLE
Cannot render redirection to async route from NavNotFoundErrorBoundary

### ISSUE THREAD

**Issue by MBO** [frontarm/navi#49] opened 2019-01-30 10:21 UTC
I have web app which instead of rendering "not found" page redirects to home page.

Example code: https://frontarm.com/demoboard/?id=1f95147d-e713-4d80-a22a-af880c6810f2

I'm trying to do it this way:

```javascript
function renderNotFound() {
  return (
    <NavHistory>{(history) => history.push('/about')}</NavHistory>
  )
} 

// [...]
<NavNotFoundBoundary render={renderNotFound}>
  <NavContent />
</NavNotFoundBoundary>
```

and it works correctly when my page's `getContent()` returns content immediately, but when I try to redirect to async page

```javascript
'/about': Navi.createPage({
      title: 'The createSwitch() function',
      getContent: () => import('./about.mdx'),
    }),
```

it fails with following errors in console:
```
Uncaught Error: URL not found: /abc/
    at createNotFoundSegment (VM168 navi.js:322)
    at class_1.NodeMatcher.getResult (VM168 navi.js:363)
    at class_1.SwitchMatcher.execute (VM168 navi.js:872)
    at class_1.NodeMatcher.getResult (VM168 navi.js:356)
    at RouteObservable.refresh (VM168 navi.js:1336)
    at RouteObservable.handleChange (VM168 navi.js:1321)
    at RouteObservable.subscribe (VM168 navi.js:1359)
    at CurrentRouteObservable.handleURLChange (VM168 navi.js:1256)
    at CurrentRouteObservable.refresh (VM168 navi.js:1180)
    at new CurrentRouteObservable (VM168 navi.js:1164)
The above error occurred in the <InnerNavContent> component:
    in InnerNavContent (created by Context.Consumer)
    in NavContent (created by Context.Consumer)
    in InnerNotFoundBoundary (created by Context.Consumer)
    in ErrorBoundary (created by Context.Consumer)
    in main (created by Context.Consumer)
    in div (created by Context.Consumer)
    in NavLoading (created by App)
    in Suspense (created by NavProvider)
    in NavProvider (created by App)
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, InnerNotFoundBoundary.

Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.

Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at invariant (VM167 react-dom.development.js:49)
    at scheduleWork (VM167 react-dom.development.js:18530)
    at Object.enqueueSetState (VM167 react-dom.development.js:12437)
    at NavProvider.Component.setState (VM166 react.development.js:460)
    at Object.NavProvider._this.handleNavigationSnapshot [as next] (VM173 react-navi.js:335)
    at MapObserver.next (VM168 navi.js:1963)
    at CurrentRouteObservable.handleURLChange (VM168 navi.js:1226)
    at VM168 navi.js:1163
    at listener (VM171 history.js:878)
    at VM171 history.js:897

The above error occurred in the <Context.Consumer> component:
    in NavHistory (created by InnerNotFoundBoundary)
    in InnerNotFoundBoundary (created by Context.Consumer)
    in ErrorBoundary (created by Context.Consumer)
    in main (created by Context.Consumer)
    in div (created by Context.Consumer)
    in NavLoading (created by App)
    in Suspense (created by NavProvider)
    in NavProvider (created by App)
    in App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

Uncaught (in promise) Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at invariant (VM167 react-dom.development.js:49)
    at scheduleWork (VM167 react-dom.development.js:18530)
    at Object.enqueueSetState (VM167 react-dom.development.js:12437)
    at NavProvider.Component.setState (VM166 react.development.js:460)
    at Object.NavProvider._this.handleNavigationSnapshot [as next] (VM173 react-navi.js:335)
    at MapObserver.next (VM168 navi.js:1963)
    at CurrentRouteObservable.handleURLChange (VM168 navi.js:1226)
    at VM168 navi.js:1163
    at listener (VM171 history.js:878)
    at VM171 history.js:897
```

**Comment by MBO** [comment] 2019-01-30 16:40
I think I made it work, with this change:

```javascript
const renderNotFound = () => (
  <NavHistory>
    {(history) => {
      if (history.location.pathname !== '/about') {
        history.replace('/about');
      }
    }}
  </NavHistory>
);
```

So instead of changing history on every render cycle (which I think makes loop with NavProvider->NavNotFoundBounndry->NavHistory->history.replace) I'm checking url first.

Maybe it makes sense to have this case covered in Readme, so if anyone tries to handle redirection on not-found route doesn't fall into this trap with async route

**Comment by jamesknelson** [comment] 2019-02-02 07:19
Thanks for filing this issue. I've run into a couple update loops myself, and I'd really like to find a longer term fix so that people don't run into them anymore.

I think part of the problem is the way the `history` package is designed, although unfortunately we're kind of stuck with it for react-router compatibility.

Until we find a better fix though, would you be able to find some time to add a note to the docs?

**Comment by xinhash** [comment] 2019-02-07 15:42
Why not include history package as some kind of middleware, like we have with Redux. Use thunk or sagas. In that case you can fix it easily. Moreover it'll pave way for further integration with history packages from other developers

**Comment by jamesknelson** [comment] 2019-02-08 07:50
@xinhash I'm curious what kind of API you're imagining?

I'm actually implementing middleware at the moment, but they're only meant to be used when performing routing, not after the route is available and is being rendered by React.

By the way, it's already possible to provide a custom `history` package - both `createBrowserHistory()` and `createMemoryHistory()` support a `history` option for you to pass in your own.

**Comment by jamesknelson** [comment] 2019-03-18 16:13
I've just added navigation loop detection, which would hopefully prevent this issue from causing any major problems. Going to close this for now, but feel free to re-open it.

**Closed by jamesknelson** 2019-03-18 16:13 UTC

**Comment by BlaineBradbury** [comment] 2019-11-06 18:35
I've not been following in detail the past months.  Are these exports from the example already outdated... or coming soon?  I get a...

> 'NavHistory' is not exported from 'react-navi'

`import { NavLink, NavProvider, NavContent, NavHistory, NavLoading, NavNotFoundBoundary } from 'react-navi'`

**Comment by jamesknelson** [comment] 2019-11-07 01:42
These have mostly just lost the Nav prefix. You can see the component names here:

https://github.com/frontarm/navi/tree/master/packages/react-navi/src
