### ISSUE TITLE
Route list

### ISSUE THREAD

**Issue by alexvandervegt** [frontarm/navi#153] opened 2019-11-28 15:43 UTC
Is it possible to get an array from the routes.js containing all the paths for navi?

**Comment by jamesknelson** [comment] 2019-11-30 10:52
It should be possible using the [crawl](https://frontarm.com/navi/en/reference/router/#crawl) function.

**Comment by jamesknelson** [comment] 2019-12-26 07:45
Closing this for now - feel free to reopen if the issue isn't resolved.

**Closed by jamesknelson** 2019-12-26 07:45 UTC
